### ISSUE TITLE
Landing Page 

### ISSUE THREAD

**Issue by SaiAbhishek98** [SaiAbhishek98/Nemuca-#1]
Landing page with white background and misplaced logo, Noticed on other devices too.

(https://user-images.githubusercontent.com/20886853/36999663-d89dcab4-20e6-11e8-8023-53b8c675d774.jpeg)

**Comment by SaiAbhishek98** [comment]
Seems like the landing page issue is related to the resolution of the screen. Not working on full HD

**Comment by krushiraj** [comment]
Fixed it.
